/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/generic-academic-cn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generic Academic Preset */
        get: operations["generic_academic_preset_api_v1_presets_generic_academic_cn_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/default-clean-cn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Cleanup Preset */
        get: operations["default_cleanup_preset_api_v1_presets_default_clean_cn_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cleanup Presets */
        get: operations["cleanup_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/candidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Template Candidate */
        post: operations["create_template_candidate_api_v1_templates_candidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/from-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Document From Text */
        post: operations["create_document_from_text_api_v1_documents_from_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Source */
        get: operations["get_document_source_api_v1_documents__document_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/format-manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Format Manifest */
        get: operations["get_format_manifest_api_v1_documents__document_id__format_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Document */
        post: operations["analyze_document_api_v1_documents__document_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/role-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Role Overrides */
        put: operations["set_role_overrides_api_v1_analyses__analysis_id__role_overrides_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Spec */
        post: operations["create_spec_api_v1_specs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specs/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compile Spec */
        post: operations["compile_spec_api_v1_specs_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specs/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Spec */
        post: operations["validate_spec_api_v1_specs_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specs/{spec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spec */
        get: operations["get_spec_api_v1_specs__spec_id__get"];
        /** Update Spec */
        put: operations["update_spec_api_v1_specs__spec_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rule Packs */
        get: operations["list_rule_packs_api_v1_rule_packs_get"];
        put?: never;
        /** Create Rule Pack */
        post: operations["create_rule_pack_api_v1_rule_packs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule Pack */
        get: operations["get_rule_pack_api_v1_rule_packs__pack_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-packs/{pack_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rule Pack Version */
        post: operations["create_rule_pack_version_api_v1_rule_packs__pack_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-packs/{pack_id}/versions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule Pack Version */
        get: operations["get_rule_pack_version_api_v1_rule_packs__pack_id__versions__revision__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-packs/{pack_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Rule Pack Version */
        post: operations["restore_rule_pack_version_api_v1_rule_packs__pack_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rule-packs/{pack_id}/versions/{revision}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Rule Pack Version */
        get: operations["export_rule_pack_version_api_v1_rule_packs__pack_id__versions__revision__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audit Document Compliance */
        post: operations["audit_document_compliance_api_v1_documents__document_id__compliance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Output */
        get: operations["get_job_output_api_v1_jobs__job_id__output_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/audit.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Audit Json */
        get: operations["get_job_audit_json_api_v1_jobs__job_id__audit_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/audit.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Audit Markdown */
        get: operations["get_job_audit_markdown_api_v1_jobs__job_id__audit_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Alignment
         * @enum {string}
         */
        Alignment: "left" | "center" | "right" | "justify";
        /**
         * AnalysisMode
         * @enum {string}
         */
        AnalysisMode: "deterministic" | "smart";
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** @default deterministic */
            mode: components["schemas"]["AnalysisMode"];
        };
        /**
         * AutoLayoutSpec
         * @description Deterministic structural layout applied before role-based formatting.
         *
         *     Structural edits are deliberately conservative: only plain body paragraphs may be split,
         *     and every split is followed by a fresh local role analysis and content-integrity check.
         */
        AutoLayoutSpec: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Split Body Paragraphs
             * @default true
             */
            split_body_paragraphs: boolean;
            /**
             * Split On Manual Breaks
             * @default true
             */
            split_on_manual_breaks: boolean;
            /**
             * Target Body Chars
             * @default 280
             */
            target_body_chars: number;
            /**
             * Max Body Chars
             * @default 480
             */
            max_body_chars: number;
        };
        /** Body_create_template_candidate_api_v1_templates_candidate_post */
        Body_create_template_candidate_api_v1_templates_candidate_post: {
            /** File */
            file: string;
        };
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /** File */
            file: string;
        };
        /** CleanupPresetCatalogItem */
        CleanupPresetCatalogItem: {
            /** Preset Id */
            preset_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Recommended Kinds */
            recommended_kinds: string[];
            metadata: components["schemas"]["RulePackMetadata"];
            spec: components["schemas"]["FormattingSpec"];
        };
        /** CleanupPresetCatalogResponse */
        CleanupPresetCatalogResponse: {
            /** Presets */
            presets: components["schemas"]["CleanupPresetCatalogItem"][];
        };
        /** CompileSpecRequest */
        CompileSpecRequest: {
            /** Document Id */
            document_id?: string | null;
            /** Analysis Id */
            analysis_id?: string | null;
            /** Instruction */
            instruction: string;
            /**
             * Apply Preset
             * @default false
             */
            apply_preset: boolean;
        };
        /** ComplianceReport */
        ComplianceReport: {
            /**
             * Schema Version
             * @default compliance-report.v1
             * @constant
             */
            schema_version: "compliance-report.v1";
            /** Document Id */
            document_id: string;
            /** Analysis Id */
            analysis_id: string;
            /** Spec Id */
            spec_id: string;
            /** Compliant */
            compliant: boolean;
            summary: components["schemas"]["ComplianceSummary"];
            /** Violations */
            violations?: components["schemas"]["ValidationIssue"][];
            /** Content Fingerprint */
            content_fingerprint?: string | null;
        };
        /** ComplianceRequest */
        ComplianceRequest: {
            /** Analysis Id */
            analysis_id: string;
            /** Spec Id */
            spec_id: string;
        };
        /** ComplianceSummary */
        ComplianceSummary: {
            /** Total Violations */
            total_violations: number;
            /** Returned Violations */
            returned_violations: number;
            /** Affected Locators */
            affected_locators: number;
            /** By Severity */
            by_severity?: {
                [key: string]: number;
            };
            /** By Code */
            by_code?: {
                [key: string]: number;
            };
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** DocumentFormattingSpec */
        DocumentFormattingSpec: {
            page?: components["schemas"]["PageFormattingSpec"];
        };
        /** FigureFormattingSpec */
        FigureFormattingSpec: {
            /**
             * Center Image Only Paragraphs
             * @default false
             */
            center_image_only_paragraphs: boolean;
        };
        /** FontSpec */
        FontSpec: {
            /** East Asia */
            east_asia?: string | null;
            /** Ascii */
            ascii?: string | null;
            /** High Ansi */
            high_ansi?: string | null;
            /** Complex Script */
            complex_script?: string | null;
            /** Size Pt */
            size_pt?: number | null;
            /** Bold */
            bold?: boolean | null;
            /** Italic */
            italic?: boolean | null;
            /** Underline */
            underline?: boolean | null;
            /** Color Hex */
            color_hex?: string | null;
        };
        /** ForcePolicy */
        ForcePolicy: {
            /** Properties */
            properties?: components["schemas"]["FormattingProperty"][];
        };
        /** FormatManifest */
        FormatManifest: {
            /**
             * Schema Version
             * @default format-manifest.v1
             * @constant
             */
            schema_version: "format-manifest.v1";
            /** Document Id */
            document_id: string;
            /** Source Filename */
            source_filename: string;
            /** Source Sha256 */
            source_sha256: string;
            /** Requirements */
            requirements?: components["schemas"]["ManifestRequirement"][];
            summary: components["schemas"]["FormatManifestSummary"];
            /** Warnings */
            warnings?: string[];
        };
        /** FormatManifestSummary */
        FormatManifestSummary: {
            /** Requirement Count */
            requirement_count: number;
            /** By Category */
            by_category?: {
                [key: string]: number;
            };
            /**
             * Auto Applicable Count
             * @default 0
             */
            auto_applicable_count: number;
        };
        /** FormattingBehavior */
        FormattingBehavior: {
            /**
             * Preserve Inline Emphasis
             * @default true
             */
            preserve_inline_emphasis: boolean;
            /**
             * Preserve Hyperlinks
             * @default true
             */
            preserve_hyperlinks: boolean;
            /**
             * Preserve Fields
             * @default true
             */
            preserve_fields: boolean;
            /**
             * Preserve Equations
             * @default true
             */
            preserve_equations: boolean;
            /**
             * Preserve Unknown Xml
             * @default true
             */
            preserve_unknown_xml: boolean;
            /**
             * Normalize Direct Paragraph Formatting
             * @default true
             */
            normalize_direct_paragraph_formatting: boolean;
            /**
             * Normalize Direct Run Formatting
             * @default true
             */
            normalize_direct_run_formatting: boolean;
            /**
             * Preserve Right Aligned Signatures
             * @default false
             */
            preserve_right_aligned_signatures: boolean;
            /**
             * Apply To Unknown Roles
             * @default false
             */
            apply_to_unknown_roles: boolean;
            /** @default body */
            unknown_role_fallback: components["schemas"]["SemanticRole"];
            /**
             * Validation Passes
             * @default 2
             */
            validation_passes: number;
            /**
             * Auto Repair
             * @default true
             */
            auto_repair: boolean;
        };
        /**
         * FormattingProperty
         * @enum {string}
         */
        FormattingProperty: "font.east_asia" | "font.ascii" | "font.high_ansi" | "font.complex_script" | "font.size_pt" | "font.bold" | "font.italic" | "font.underline" | "font.color_hex" | "paragraph.alignment" | "paragraph.line_spacing" | "paragraph.space_before_pt" | "paragraph.space_after_pt" | "paragraph.first_line_indent_pt" | "paragraph.left_indent_pt" | "paragraph.right_indent_pt";
        /** FormattingSpec */
        FormattingSpec: {
            /**
             * Schema Version
             * @default formatting-spec.v1
             * @constant
             */
            schema_version: "formatting-spec.v1";
            document?: components["schemas"]["DocumentFormattingSpec"] | null;
            baseline?: components["schemas"]["RoleFormattingSpec"] | null;
            /** Roles */
            roles?: {
                [key: string]: components["schemas"]["RoleFormattingSpec"];
            };
            tables?: components["schemas"]["TableFormattingSpec"] | null;
            figures?: components["schemas"]["FigureFormattingSpec"] | null;
            headers?: components["schemas"]["HeaderFooterFormattingSpec"] | null;
            footers?: components["schemas"]["HeaderFooterFormattingSpec"] | null;
            page_numbers?: components["schemas"]["PageNumberSpec"] | null;
            visual_cleanup?: components["schemas"]["VisualCleanupSpec"] | null;
            auto_layout?: components["schemas"]["AutoLayoutSpec"];
            behavior?: components["schemas"]["FormattingBehavior"];
            source?: components["schemas"]["SpecSource"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeaderFooterFormattingSpec */
        HeaderFooterFormattingSpec: {
            font?: components["schemas"]["FontSpec"] | null;
            paragraph?: components["schemas"]["ParagraphSpec"] | null;
        };
        /** JobChangeDetail */
        JobChangeDetail: {
            /** Locator */
            locator: string | null;
            /** Node Id */
            node_id: string | null;
            /** Category */
            category: string;
            /** Property Path */
            property_path: string;
            /** Before Value */
            before_value: string | null;
            /** After Value */
            after_value: string | null;
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Document Id */
            document_id: string;
            /** Analysis Id */
            analysis_id: string;
            /** Spec Id */
            spec_id: string;
        };
        /** JobResponse */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Document Id */
            document_id: string;
            /** Analysis Id */
            analysis_id: string;
            /** Spec Id */
            spec_id: string;
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Auto Layout Splits */
            auto_layout_splits: number;
            result_summary: components["schemas"]["JobResultSummary"] | null;
            /** Output Document Url */
            output_document_url: string | null;
            /** Audit Json Url */
            audit_json_url: string | null;
            /** Audit Markdown Url */
            audit_markdown_url: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobResultSummary */
        JobResultSummary: {
            /** Validation Passed */
            validation_passed: boolean;
            /** Content Integrity Passed */
            content_integrity_passed: boolean;
            /** Format Operations */
            format_operations: number;
            /** Changed Mutations */
            changed_mutations: number;
            /** Change Categories */
            change_categories: {
                [key: string]: number;
            };
            /** Change Details */
            change_details: components["schemas"]["JobChangeDetail"][];
            /** Change Details Truncated */
            change_details_truncated: boolean;
            /** Warning Count */
            warning_count: number;
            /** Validation Issue Count */
            validation_issue_count: number;
            /** Remaining Review Items */
            remaining_review_items: number;
            /** Paragraphs Before */
            paragraphs_before: number | null;
            /** Paragraphs After */
            paragraphs_after: number | null;
            /** Auto Layout Splits */
            auto_layout_splits: number;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "analyzing" | "planning" | "formatting" | "validating" | "repairing" | "completed" | "failed";
        /**
         * LineSpacingMode
         * @enum {string}
         */
        LineSpacingMode: "single" | "multiple" | "exact" | "at_least";
        /** LineSpacingSpec */
        LineSpacingSpec: {
            mode: components["schemas"]["LineSpacingMode"];
            /** Value */
            value?: number | null;
        };
        /** ManifestRequirement */
        ManifestRequirement: {
            /** Requirement Id */
            requirement_id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "style" | "section" | "table" | "numbering" | "header_footer";
            /** Target */
            target: string;
            /** Target Label */
            target_label?: string | null;
            /** Property Path */
            property_path: string;
            /** Expected */
            expected: unknown;
            /** Source Part */
            source_part: string;
            /** Evidence */
            evidence: string;
            /** Confidence */
            confidence: number;
            /**
             * Auto Applicable
             * @default false
             */
            auto_applicable: boolean;
        };
        /**
         * Orientation
         * @enum {string}
         */
        Orientation: "portrait" | "landscape";
        /** PageFormattingSpec */
        PageFormattingSpec: {
            size?: components["schemas"]["PageSize"] | null;
            orientation?: components["schemas"]["Orientation"] | null;
            /** Margin Top Mm */
            margin_top_mm?: number | null;
            /** Margin Bottom Mm */
            margin_bottom_mm?: number | null;
            /** Margin Left Mm */
            margin_left_mm?: number | null;
            /** Margin Right Mm */
            margin_right_mm?: number | null;
            /** Header Distance Mm */
            header_distance_mm?: number | null;
            /** Footer Distance Mm */
            footer_distance_mm?: number | null;
            /**
             * Preserve Existing Landscape Sections
             * @default true
             */
            preserve_existing_landscape_sections: boolean;
            /**
             * Force Orientation All Sections
             * @default false
             */
            force_orientation_all_sections: boolean;
        };
        /** PageNumberSpec */
        PageNumberSpec: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Location
             * @default footer
             * @constant
             */
            location: "footer";
            /** @default center */
            alignment: components["schemas"]["Alignment"];
            /**
             * Number Format
             * @default decimal
             * @constant
             */
            number_format: "decimal";
            /** Start At */
            start_at?: number | null;
        };
        /**
         * PageSize
         * @enum {string}
         */
        PageSize: "A4" | "LETTER";
        /** ParagraphSpec */
        ParagraphSpec: {
            alignment?: components["schemas"]["Alignment"] | null;
            line_spacing?: components["schemas"]["LineSpacingSpec"] | null;
            /** Space Before Pt */
            space_before_pt?: number | null;
            /** Space After Pt */
            space_after_pt?: number | null;
            /** First Line Indent Pt */
            first_line_indent_pt?: number | null;
            /** Hanging Indent Pt */
            hanging_indent_pt?: number | null;
            /** Left Indent Pt */
            left_indent_pt?: number | null;
            /** Right Indent Pt */
            right_indent_pt?: number | null;
            /** Keep With Next */
            keep_with_next?: boolean | null;
            /** Keep Lines Together */
            keep_lines_together?: boolean | null;
            /** Page Break Before */
            page_break_before?: boolean | null;
            /** Widow Orphan Control */
            widow_orphan_control?: boolean | null;
        };
        /** RoleFormattingSpec */
        RoleFormattingSpec: {
            font?: components["schemas"]["FontSpec"] | null;
            paragraph?: components["schemas"]["ParagraphSpec"] | null;
            /** Style Name */
            style_name?: string | null;
            force?: components["schemas"]["ForcePolicy"];
        };
        /** RoleOverride */
        RoleOverride: {
            /** Node Id */
            node_id: string;
            role: components["schemas"]["SemanticRole"];
        };
        /** RoleOverrideRequest */
        RoleOverrideRequest: {
            /** Overrides */
            overrides?: components["schemas"]["RoleOverride"][];
        };
        /**
         * RulePackApprovalStatus
         * @enum {string}
         */
        RulePackApprovalStatus: "draft" | "locally_approved";
        /**
         * RulePackArtifact
         * @description Portable, integrity-checked snapshot of one immutable rule-pack revision.
         */
        RulePackArtifact: {
            /**
             * Schema Version
             * @default rule-pack.v1
             * @constant
             */
            schema_version: "rule-pack.v1";
            /** Pack Id */
            pack_id: string;
            /** Request Id */
            request_id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Scope Label */
            scope_label: string;
            /** Revision */
            revision: number;
            /** @default draft */
            approval_status: components["schemas"]["RulePackApprovalStatus"];
            /** Approval Note */
            approval_note?: string | null;
            /** Change Note */
            change_note: string;
            /** Restored From Revision */
            restored_from_revision?: number | null;
            /** Spec Sha256 */
            spec_sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            spec: components["schemas"]["FormattingSpec"];
        };
        /** RulePackCatalogItem */
        RulePackCatalogItem: {
            /** Pack Id */
            pack_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Scope Label */
            scope_label: string;
            /** Current Revision */
            current_revision: number;
            current_approval_status: components["schemas"]["RulePackApprovalStatus"];
            /** Current Spec Sha256 */
            current_spec_sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RulePackCatalogResponse */
        RulePackCatalogResponse: {
            /** Rule Packs */
            rule_packs: components["schemas"]["RulePackCatalogItem"][];
        };
        /**
         * RulePackClaimLevel
         * @enum {string}
         */
        RulePackClaimLevel: "generic" | "reference" | "verified";
        /** RulePackCreateRequest */
        RulePackCreateRequest: {
            /** Request Id */
            request_id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Scope Label */
            scope_label: string;
            spec: components["schemas"]["FormattingSpec"];
            /**
             * Change Note
             * @default 创建初始修订
             */
            change_note: string;
            /** @default draft */
            approval_status: components["schemas"]["RulePackApprovalStatus"];
            /** Approval Note */
            approval_note?: string | null;
        };
        /** RulePackDetailResponse */
        RulePackDetailResponse: {
            /** Pack Id */
            pack_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Scope Label */
            scope_label: string;
            /** Current Revision */
            current_revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions: components["schemas"]["RulePackVersionSummary"][];
        };
        /** RulePackMetadata */
        RulePackMetadata: {
            /** Pack Version */
            pack_version: string;
            claim_level: components["schemas"]["RulePackClaimLevel"];
            /** Scope Label */
            scope_label: string;
            /** Maintained By */
            maintained_by: string;
            /**
             * Last Reviewed On
             * Format: date
             */
            last_reviewed_on: string;
            /** Source References */
            source_references: components["schemas"]["RulePackReference"][];
            /** Covered Capabilities */
            covered_capabilities: string[];
            /** Limitations */
            limitations: string[];
        };
        /** RulePackReference */
        RulePackReference: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Version */
            version?: string | null;
        };
        /** RulePackRestoreRequest */
        RulePackRestoreRequest: {
            /** Request Id */
            request_id: string;
            /** Revision */
            revision: number;
            /**
             * Change Note
             * @default 恢复历史修订
             */
            change_note: string;
        };
        /** RulePackVersionCreateRequest */
        RulePackVersionCreateRequest: {
            /** Request Id */
            request_id: string;
            spec: components["schemas"]["FormattingSpec"];
            /** Change Note */
            change_note: string;
            /** @default draft */
            approval_status: components["schemas"]["RulePackApprovalStatus"];
            /** Approval Note */
            approval_note?: string | null;
        };
        /** RulePackVersionSummary */
        RulePackVersionSummary: {
            /** Revision */
            revision: number;
            approval_status: components["schemas"]["RulePackApprovalStatus"];
            /** Approval Note */
            approval_note: string | null;
            /** Change Note */
            change_note: string;
            /** Restored From Revision */
            restored_from_revision?: number | null;
            /** Spec Sha256 */
            spec_sha256: string;
            /** Source Type */
            source_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SemanticRole
         * @enum {string}
         */
        SemanticRole: "cover" | "title" | "subtitle" | "author_info" | "abstract_heading" | "abstract_body" | "keywords" | "heading_1" | "heading_2" | "heading_3" | "heading_4" | "body" | "blockquote" | "list_item" | "figure_caption" | "table_caption" | "bibliography_heading" | "bibliography_entry" | "appendix_heading" | "appendix_body" | "header" | "footer" | "unknown";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "fatal" | "error" | "warning" | "info";
        /** SpecSource */
        SpecSource: {
            /** @default structured */
            type: components["schemas"]["SpecSourceType"];
            /** Preset Id */
            preset_id?: string | null;
            /** Instruction Hash */
            instruction_hash?: string | null;
            /** Compiler Version */
            compiler_version?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Reference Filename */
            reference_filename?: string | null;
            /** Reference Sha256 */
            reference_sha256?: string | null;
            /** Assumptions */
            assumptions?: string[];
        };
        /**
         * SpecSourceType
         * @enum {string}
         */
        SpecSourceType: "system" | "preset" | "natural_language" | "template" | "structured" | "merged";
        /** StructuredSpecRequest */
        StructuredSpecRequest: {
            /** Document Id */
            document_id?: string | null;
            spec: components["schemas"]["FormattingSpec"];
        };
        /** TableFormattingSpec */
        TableFormattingSpec: {
            alignment?: components["schemas"]["Alignment"] | null;
            /** @default preserve */
            width_policy: components["schemas"]["TableWidthPolicy"];
            /** Fixed Width Mm */
            fixed_width_mm?: number | null;
            /** Cell Vertical Alignment */
            cell_vertical_alignment?: ("top" | "center" | "bottom") | null;
            font?: components["schemas"]["FontSpec"] | null;
            paragraph?: components["schemas"]["ParagraphSpec"] | null;
            /**
             * Grid Borders
             * @default false
             */
            grid_borders: boolean;
            /**
             * Repeat Header Row
             * @default false
             */
            repeat_header_row: boolean;
            /**
             * Prevent Row Split
             * @default false
             */
            prevent_row_split: boolean;
            /**
             * Adaptive Column Widths
             * @default false
             */
            adaptive_column_widths: boolean;
            /**
             * Min Column Width Mm
             * @default 8
             */
            min_column_width_mm: number;
            /**
             * Adaptive Font Size
             * @default false
             */
            adaptive_font_size: boolean;
            /**
             * Min Font Size Pt
             * @default 8.5
             */
            min_font_size_pt: number;
        };
        /**
         * TableWidthPolicy
         * @enum {string}
         */
        TableWidthPolicy: "preserve" | "fit_printable_width" | "fixed";
        /** TemplateCandidateSummary */
        TemplateCandidateSummary: {
            /** Source Requirement Count */
            source_requirement_count: number;
            /** Auto Applicable Requirement Count */
            auto_applicable_requirement_count: number;
            /** Applied Requirement Count */
            applied_requirement_count: number;
            /** Mapped Role Count */
            mapped_role_count: number;
            /** Coverage Percent */
            coverage_percent: number;
        };
        /** TemplateRoleMapping */
        TemplateRoleMapping: {
            role: components["schemas"]["SemanticRole"];
            /** Source Style Name */
            source_style_name: string;
            /** Paragraph Count */
            paragraph_count: number;
            /** Confidence */
            confidence: number;
            /** Included Properties */
            included_properties?: string[];
        };
        /** TemplateRuleCandidate */
        TemplateRuleCandidate: {
            /**
             * Schema Version
             * @default template-rule-candidate.v1
             * @constant
             */
            schema_version: "template-rule-candidate.v1";
            /** Source Filename */
            source_filename: string;
            /** Source Sha256 */
            source_sha256: string;
            /** Safe To Apply */
            safe_to_apply: boolean;
            spec: components["schemas"]["FormattingSpec"];
            summary: components["schemas"]["TemplateCandidateSummary"];
            /** Role Mappings */
            role_mappings?: components["schemas"]["TemplateRoleMapping"][];
            /** Applied Requirement Ids */
            applied_requirement_ids?: string[];
            /** Ambiguities */
            ambiguities?: string[];
            /** Unsupported Features */
            unsupported_features?: string[];
            /** Warnings */
            warnings?: string[];
        };
        /** TextDocumentRequest */
        TextDocumentRequest: {
            /** Text */
            text: string;
            /**
             * Filename
             * @default 未命名文档.docx
             */
            filename: string;
        };
        /** ValidateSpecRequest */
        ValidateSpecRequest: {
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            severity: components["schemas"]["Severity"];
            /** Message */
            message: string;
            /** Node Id */
            node_id?: string | null;
            /** Locator */
            locator?: string | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** VisualCleanupSpec */
        VisualCleanupSpec: {
            /** Text Color Hex */
            text_color_hex?: string | null;
            /**
             * Remove Text Highlight
             * @default false
             */
            remove_text_highlight: boolean;
            /**
             * Remove Character Shading
             * @default false
             */
            remove_character_shading: boolean;
            /**
             * Remove Paragraph Shading
             * @default false
             */
            remove_paragraph_shading: boolean;
            /**
             * Remove Table Cell Shading
             * @default false
             */
            remove_table_cell_shading: boolean;
            /**
             * Remove Page Background
             * @default false
             */
            remove_page_background: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    generic_academic_preset_api_v1_presets_generic_academic_cn_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    default_cleanup_preset_api_v1_presets_default_clean_cn_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cleanup_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupPresetCatalogResponse"];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_candidate_api_v1_templates_candidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_template_candidate_api_v1_templates_candidate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRuleCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_from_text_api_v1_documents_from_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_source_api_v1_documents__document_id__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_format_manifest_api_v1_documents__document_id__format_manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormatManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_document_api_v1_documents__document_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_overrides_api_v1_analyses__analysis_id__role_overrides_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_spec_api_v1_specs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructuredSpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_spec_api_v1_specs_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileSpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_spec_api_v1_specs_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateSpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spec_api_v1_specs__spec_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spec_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_spec_api_v1_specs__spec_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spec_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructuredSpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rule_packs_api_v1_rule_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackCatalogResponse"];
                };
            };
        };
    };
    create_rule_pack_api_v1_rule_packs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePackCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_pack_api_v1_rule_packs__pack_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_pack_version_api_v1_rule_packs__pack_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePackVersionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_pack_version_api_v1_rule_packs__pack_id__versions__revision__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_rule_pack_version_api_v1_rule_packs__pack_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePackRestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_rule_pack_version_api_v1_rule_packs__pack_id__versions__revision__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_document_compliance_api_v1_documents__document_id__compliance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplianceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_output_api_v1_jobs__job_id__output_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_audit_json_api_v1_jobs__job_id__audit_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_audit_markdown_api_v1_jobs__job_id__audit_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
